"""
Institutions and employers — the issuing side of the platform.

This app is where the proposal's biggest unstated requirement lives (HR-01).
Proposal §2.3 calls the absence of a central verification authority the problem,
while §4.1 requires that "only registered institutions can push credentials".
Registration implies an approver, so there is a ``PENDING → APPROVED`` workflow
gated by a platform registrar who checks accreditation documents off-platform.

Without that gate, anyone could self-register as "Tribhuvan University" and mint
degrees, and the platform would launder forgeries instead of preventing them. The
blockchain removes the *verification bottleneck*; it does not remove the need for
a root of trust.
"""

from django.core.validators import MinLengthValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from apps.common.models import BaseModel
from apps.common.utils import normalise_text
from apps.common.validators import UploadValidator, validate_eth_address


class OrganizationKind(models.TextChoices):
    INSTITUTION = "INSTITUTION", _("Educational institution")
    EMPLOYER = "EMPLOYER", _("Employer")


class OrganizationStatus(models.TextChoices):
    PENDING = "PENDING", _("Pending review")
    APPROVED = "APPROVED", _("Approved")
    SUSPENDED = "SUSPENDED", _("Suspended")
    REJECTED = "REJECTED", _("Rejected")


class MembershipRole(models.TextChoices):
    OWNER = "OWNER", _("Owner")
    ISSUER = "ISSUER", _("Issuer")
    VIEWER = "VIEWER", _("Viewer")


class Plan(models.TextChoices):
    FREE = "FREE", _("Free")
    PRO = "PRO", _("Pro")


class Organization(BaseModel):
    """An institution or employer. One row per legal entity."""

    kind = models.CharField(max_length=20, choices=OrganizationKind.choices)
    legal_name = models.CharField(max_length=200, validators=[MinLengthValidator(3)])
    slug = models.SlugField(max_length=80, unique=True)
    registration_number = models.CharField(
        max_length=64,
        help_text=_("PAN/VAT number for employers, UGC accreditation number for institutions."),
    )
    website = models.URLField(blank=True)
    contact_email = models.EmailField()
    contact_phone = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=255, blank=True)

    status = models.CharField(
        max_length=20, choices=OrganizationStatus.choices, default=OrganizationStatus.PENDING
    )
    status_reason = models.TextField(
        blank=True, help_text=_("Why the organisation was rejected or suspended.")
    )

    # ---- chain identity -----------------------------------------------------
    chain_address = models.CharField(
        max_length=42,
        blank=True,
        validators=[validate_eth_address],
        help_text=_("Custodial signing address. Generated by the platform on approval."),
    )
    approval_tx_hash = models.CharField(max_length=66, blank=True)
    approved_on_chain_at = models.DateTimeField(null=True, blank=True)

    approved_by = models.ForeignKey(
        "accounts.User",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="approved_organizations",
    )
    approved_at = models.DateTimeField(null=True, blank=True)
    suspended_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "organizations_organization"
        ordering = ["legal_name"]
        constraints = [
            models.UniqueConstraint(
                fields=["kind", "registration_number"],
                name="org_unique_registration_per_kind",
            ),
            models.UniqueConstraint(
                fields=["chain_address"],
                condition=~models.Q(chain_address=""),
                name="org_unique_chain_address_when_set",
            ),
            # An APPROVED organisation without a signing address cannot issue,
            # and would fail confusingly at the first anchor attempt instead of
            # at the moment the invariant was broken.
            models.CheckConstraint(
                check=~models.Q(status="APPROVED") | ~models.Q(chain_address=""),
                name="org_approved_requires_chain_address",
            ),
        ]
        indexes = [
            models.Index(fields=["status", "kind"]),
            models.Index(fields=["kind"]),
        ]

    def __str__(self) -> str:
        return f"{self.legal_name} ({self.get_kind_display()})"

    def save(self, *args, **kwargs):
        self.legal_name = normalise_text(self.legal_name)
        super().save(*args, **kwargs)

    @property
    def can_issue(self) -> bool:
        return self.status == OrganizationStatus.APPROVED and bool(self.chain_address)

    @property
    def issues_academic(self) -> bool:
        return self.kind == OrganizationKind.INSTITUTION

    def mark_approved(self, *, registrar, tx_hash: str, chain_address: str) -> None:
        self.status = OrganizationStatus.APPROVED
        self.chain_address = chain_address
        self.approval_tx_hash = tx_hash
        self.approved_by = registrar
        self.approved_at = timezone.now()
        self.approved_on_chain_at = timezone.now()
        self.status_reason = ""
        self.suspended_at = None
        self.save(
            update_fields=[
                "status",
                "chain_address",
                "approval_tx_hash",
                "approved_by",
                "approved_at",
                "approved_on_chain_at",
                "status_reason",
                "suspended_at",
                "updated_at",
            ]
        )


class IssuerKey(BaseModel):
    """
    The custodial signing key for an organisation.

    Held by the platform, not the university. Proposal §8 names "universities
    unfamiliar with blockchain" as a Phase I blocker, and no registrar's office
    in Nepal is going to manage a private key or buy gas tokens. So the platform
    generates the key, encrypts it at rest, signs on the organisation's behalf,
    and pays the gas.

    That is a real, deliberate centralisation trade-off, and it is stated plainly
    in ``docs/SECURITY.md`` rather than glossed over: the platform can technically
    sign as any issuer. Mitigations are envelope encryption with a key outside
    the database, an append-only audit trail of every signature, and a documented
    migration path to per-issuer HSM/KMS keys before any real deployment.

    Kept in its own table so ordinary organisation queries never load key
    material, and so the table can be moved to a separate database or replaced
    by a KMS reference without touching ``Organization``.
    """

    organization = models.OneToOneField(
        Organization, on_delete=models.CASCADE, related_name="issuer_key"
    )
    address = models.CharField(max_length=42, validators=[validate_eth_address])
    encrypted_private_key = models.BinaryField(
        help_text=_("Fernet ciphertext. The key never exists in plaintext at rest.")
    )
    key_version = models.PositiveSmallIntegerField(default=1)
    last_used_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "organizations_issuerkey"

    def __str__(self) -> str:
        return f"Signing key v{self.key_version} for {self.organization.legal_name}"


class OrganizationDocument(BaseModel):
    """Accreditation evidence the registrar reviews before approving."""

    class DocType(models.TextChoices):
        ACCREDITATION = "ACCREDITATION", _("Accreditation certificate")
        REGISTRATION = "REGISTRATION", _("Company/PAN registration")
        AUTHORISATION = "AUTHORISATION", _("Letter of authorisation")
        OTHER = "OTHER", _("Other")

    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="documents"
    )
    doc_type = models.CharField(max_length=20, choices=DocType.choices)
    file = models.FileField(upload_to="org-documents/%Y/%m/", validators=[UploadValidator()])
    sha256 = models.CharField(max_length=64, blank=True)
    uploaded_by = models.ForeignKey(
        "accounts.User", null=True, on_delete=models.SET_NULL, related_name="+"
    )

    class Meta:
        db_table = "organizations_document"
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return f"{self.get_doc_type_display()} — {self.organization.legal_name}"


class OrganizationMembership(BaseModel):
    """
    Links a user to an organisation with a role.

    Authority to issue is the conjunction of this row's role and the
    organisation's status, evaluated per request. Suspending an organisation
    therefore disables all of its staff at once, with no user records touched and
    nothing to forget to revoke.
    """

    user = models.ForeignKey("accounts.User", on_delete=models.CASCADE, related_name="memberships")
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="memberships"
    )
    role = models.CharField(
        max_length=20, choices=MembershipRole.choices, default=MembershipRole.ISSUER
    )
    invited_by = models.ForeignKey(
        "accounts.User", null=True, blank=True, on_delete=models.SET_NULL, related_name="+"
    )

    class Meta:
        db_table = "organizations_membership"
        constraints = [
            models.UniqueConstraint(
                fields=["user", "organization"], name="membership_unique_user_org"
            )
        ]
        indexes = [models.Index(fields=["organization", "role"])]

    def __str__(self) -> str:
        return f"{self.user.email} @ {self.organization.slug} ({self.role})"

    @property
    def can_issue(self) -> bool:
        return (
            self.role in {MembershipRole.OWNER, MembershipRole.ISSUER}
            and self.organization.can_issue
        )


class Subscription(BaseModel):
    """
    Employer billing tier — proposal §9.

    Job seekers are free and institutions are free (they are the supply side;
    charging them blocks onboarding). Only verification volume is metered, which
    is why this model hangs off ``Organization`` and nothing else.
    """

    organization = models.OneToOneField(
        Organization, on_delete=models.CASCADE, related_name="subscription"
    )
    plan = models.CharField(max_length=10, choices=Plan.choices, default=Plan.FREE)
    monthly_lookup_limit = models.PositiveIntegerField(
        default=50, help_text=_("0 means unlimited (PRO).")
    )
    started_at = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = "organizations_subscription"

    def __str__(self) -> str:
        return f"{self.organization.slug}: {self.plan}"

    @property
    def is_unlimited(self) -> bool:
        return self.plan == Plan.PRO or self.monthly_lookup_limit == 0
