# Generated by Django 5.1.4 on 2026-07-30 13:56

import apps.common.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('credentials', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=apps.common.utils.generate_token, editable=False, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, help_text="For the seeker's own reference, e.g. 'Deerwalk application'.", max_length=100)),
                ('include_all', models.BooleanField(default=True, help_text='Share everything, including records issued after this link was created.')),
                ('mask_identifiers', models.BooleanField(default=True, help_text='Mask registration and national ID numbers in the shared view (§6.3).')),
                ('passphrase_hash', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null means no expiry.', null=True)),
                ('max_views', models.PositiveIntegerField(blank=True, help_text='Null means unlimited.', null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='accounts.seekerprofile')),
            ],
            options={
                'db_table': 'verification_sharelink',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareLinkRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_selections', to='credentials.credentialrecord')),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='verification.sharelink')),
            ],
            options={
                'db_table': 'verification_sharelinkrecord',
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('lookup_reference', models.CharField(blank=True, help_text='What the verifier actually typed or scanned.', max_length=128)),
                ('result', models.CharField(choices=[('VERIFIED', 'Verified'), ('TAMPERED', 'Data does not match the ledger'), ('REVOKED', 'Revoked by the issuer'), ('SUPERSEDED', 'Superseded by a corrected record'), ('UNCONFIRMED', 'Signature valid, ledger unreachable'), ('NOT_FOUND', 'No such record')], max_length=20)),
                ('client_ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('counts_against_quota', models.BooleanField(default=False, help_text="Only authenticated employer lookups are metered. Anonymous scans are rate-limited instead, so a candidate sharing their own link with a recruiter never burns the recruiter's quota unexpectedly.")),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='credentials.credentialrecord')),
                ('share_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to='verification.sharelink')),
                ('verifier_org', models.ForeignKey(blank=True, help_text='Null for an anonymous QR scan — no account is required to verify.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_performed', to='organizations.organization')),
                ('verifier_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['seeker', '-created_at'], name='verificatio_seeker__05936b_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['expires_at'], name='verificatio_expires_d6b699_idx'),
        ),
        migrations.AddConstraint(
            model_name='sharelinkrecord',
            constraint=models.UniqueConstraint(fields=('share_link', 'record'), name='sharelink_record_unique'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['verifier_org', '-created_at'], name='verificatio_verifie_c35086_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['result', '-created_at'], name='verificatio_result_b17b31_idx'),
        ),
    ]
