# Generated by Django 5.1.4 on 2026-08-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationlog',
            name='result',
            field=models.CharField(choices=[('VERIFIED', 'Verified'), ('SUBJECT_MISMATCH', 'Genuine, but not issued to that person'), ('TAMPERED', 'Data does not match the ledger'), ('REVOKED', 'Revoked by the issuer'), ('SUPERSEDED', 'Superseded by a corrected record'), ('UNCONFIRMED', 'Signature valid, ledger unreachable'), ('NOT_FOUND', 'No such record')], max_length=20),
        ),
    ]
