"use client";

import { AccountChip } from "@/components/shell/account-chip";
import { useMyOrganization } from "@/lib/api/hooks";

/**
 * The issuer's chip, showing the address its credentials are signed by.
 *
 * That address is **not** a browser wallet. This console previously sat behind a
 * MetaMask connect gate, which contradicted the backend outright: signing keys
 * are custodial (`apps/organizations/keys.py`), generated by the platform when
 * the registrar approves an organisation, and the anchor transaction is
 * submitted server-side. A university registrar is never asked to install an
 * extension, hold a seed phrase, or think about gas — which is the point of the
 * custodial design, and stated as such in the security notes. The gate would
 * have locked every issuer out of a console that needs no wallet at all.
 *
 * So the address is shown as evidence rather than collected as input: it is what
 * a verifier sees against every credential this organisation issues, and having
 * it visible is what lets staff confirm it is the right one.
 */
export function IssuerAccountChip() {
  const { data: organization } = useMyOrganization();

  return (
    <AccountChip
      {...(organization?.chain_address ? { wallet: organization.chain_address } : {})}
      {...(organization?.legal_name ? { subtitle: organization.legal_name } : {})}
    />
  );
}
