# Generated by Django 5.1.4 on 2026-07-30 13:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('USER_REGISTERED', 'User registered'), ('USER_LOGGED_IN', 'User logged in'), ('ORG_APPLIED', 'Organisation applied'), ('ORG_APPROVED', 'Organisation approved'), ('ORG_REJECTED', 'Organisation rejected'), ('ORG_SUSPENDED', 'Organisation suspended'), ('ORG_REINSTATED', 'Organisation reinstated'), ('ISSUER_KEY_CREATED', 'Issuer signing key created'), ('RECORD_DRAFTED', 'Record drafted'), ('RECORD_CLAIMED', 'Record claimed by seeker'), ('RECORD_ENDORSED', 'Claim endorsed by issuer'), ('RECORD_CLAIM_REJECTED', 'Claim rejected by issuer'), ('RECORD_ANCHORED', 'Record anchored on chain'), ('RECORD_ANCHOR_FAILED', 'Anchor attempt failed'), ('RECORD_REVOKED', 'Record revoked'), ('RECORD_SUPERSEDED', 'Record superseded'), ('BATCH_UPLOADED', 'Batch uploaded'), ('SHARE_LINK_CREATED', 'Share link created'), ('SHARE_LINK_REVOKED', 'Share link revoked'), ('VERIFICATION_PERFORMED', 'Verification performed')], db_index=True, max_length=32)),
                ('actor_label', models.CharField(blank=True, help_text='Denormalised actor identity. Kept because the FK is SET_NULL on user deletion, and an audit entry that loses its actor is worthless.', max_length=254)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('client_ip_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organization')),
            ],
            options={
                'db_table': 'audit_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audit_event_object__f2d1b4_idx'), models.Index(fields=['organization', '-created_at'], name='audit_event_organiz_ff8aa6_idx'), models.Index(fields=['action', '-created_at'], name='audit_event_action_5d1926_idx')],
            },
        ),
    ]
