# Generated by Django 5.1.4 on 2026-07-30 13:56

import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevocationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('tx_hash', models.CharField(blank=True, max_length=66)),
                ('confirmed_on_chain', models.BooleanField(default=False)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revocations', to='credentials.credentialrecord')),
                ('revoked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ledger_revocationevent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAnchor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_hash', models.CharField(db_index=True, max_length=64, validators=[apps.common.validators.validate_record_hash])),
                ('state', models.CharField(choices=[('PENDING', 'Pending submission'), ('CONFIRMED', 'Confirmed on chain'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('chain_id', models.BigIntegerField(blank=True, null=True)),
                ('contract_address', models.CharField(blank=True, max_length=42)),
                ('tx_hash', models.CharField(blank=True, db_index=True, max_length=66)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('issuer_address', models.CharField(blank=True, max_length=42)),
                ('issuer_signature', models.CharField(blank=True, help_text='EIP-191 signature over the record hash by the issuer key. Lets a verifier confirm authenticity from a QR code alone when the chain is unreachable (HR-08).', max_length=132)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchors', to='credentials.credentialrecord')),
            ],
            options={
                'db_table': 'ledger_anchor',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', 'attempts'], name='ledger_anch_state_534aad_idx'), models.Index(fields=['record', '-created_at'], name='ledger_anch_record__747a49_idx')],
            },
        ),
    ]
