# Generated by Django 5.1.4 on 2026-07-30 13:56

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('SEEKER', 'Job seeker'), ('ORG_MEMBER', 'Organisation member'), ('REGISTRAR', 'Platform registrar')], default='SEEKER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Grants access to the registrar console at /admin/.')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'accounts_user',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SeekerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_slug', models.SlugField(help_text='Used in the passport URL. Random, not derived from the name.', max_length=64, unique=True)),
                ('headline', models.CharField(blank=True, max_length=160)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, help_text='Citizenship or national ID number. Masked whenever shared.', max_length=32)),
                ('is_discoverable', models.BooleanField(default=False, help_text="Opt in to appearing in employer candidate search. Off by default: an open, searchable national credential registry would let anyone enumerate every citizen's education history (HR-07).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_seekerprofile',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='seekerprofile',
            index=models.Index(fields=['is_discoverable'], name='accounts_se_is_disc_a94b78_idx'),
        ),
        migrations.AddConstraint(
            model_name='seekerprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('national_id', ''), _negated=True), fields=('national_id',), name='seeker_national_id_unique_when_set'),
        ),
    ]
