"""
Email-primary accounts with optional, issuer-attested citizenship.

Replaces the citizenship-keyed identity model from 0002. The account is now an
email address; the citizenship number is optional and, where present, attested
by an approved issuer rather than asserted by the holder. ``identity_level``
records which of those a given account supports so verification results can
state the limit instead of implying a subject guarantee that was never
established.

## Why this drops rows again

Profiles created under 0002 have a mandatory citizenship number and may have no
user at all — 0002 deliberately allowed issuer-created shells with no login. The
new model requires a user and permits no citizenship number, so a shell has
nothing to become. There is no released version and no deployment; the way to
repopulate is ``manage.py seed_demo``.

Deleting them also has to happen before ``AlterField`` on ``user``, which is
being made NOT NULL: any surviving shell would fail the constraint.

## What was removed and why

* ``WalletNonce`` / ``IdentityClaim`` — the SIWE sign-in and claim-code flows.
  Every role now authenticates with email and password, and issuers anchor via
  the platform's custodial keys, so neither model had a caller. An unused
  authentication table is not neutral: it is an attack surface nobody is
  reviewing.
* ``wallet_address``, ``binding_state``, ``bound_at``, ``bound_via`` — the
  wallet-binding state machine those flows drove.
* ``primary_email`` / ``primary_phone`` — now single-sourced from ``User.email``
  and ``User.phone``. Two columns holding one fact is two columns that disagree.
"""

# Generated by Django 5.1.4 on 2026-08-01 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_incompatible_profiles(apps, schema_editor):
    """
    Delete 0002-era profiles. See the module docstring for why they cannot be
    carried forward.

    ``SET CONSTRAINTS ALL IMMEDIATE`` drains the deferred foreign-key trigger
    events this cascade queues; without it the next ALTER TABLE in this
    migration fails with "cannot ALTER TABLE because it has pending trigger
    events" on PostgreSQL.
    """
    apps.get_model("accounts", "SeekerProfile").objects.all().delete()
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


def noop_reverse(apps, schema_editor):
    """Reversing cannot restore deleted rows; failing loudly would only strand
    a developer rolling the schema back."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_citizen_identity'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        # Must precede AlterField on `user` (now NOT NULL) and the new partial
        # unique on national_id_hmac. See the module docstring.
        migrations.RunPython(drop_incompatible_profiles, noop_reverse),
        # Deleted whole rather than field-by-field. Stripping an FK first makes
        # SQLite rebuild the table while `identityclaim_one_open_per_identity`
        # still references the removed column, which fails during test-database
        # construction.
        migrations.DeleteModel(name='IdentityClaim'),
        migrations.DeleteModel(name='WalletNonce'),
        migrations.RemoveConstraint(
            model_name='seekerprofile',
            name='identity_national_id_unique',
        ),
        migrations.RemoveConstraint(
            model_name='seekerprofile',
            name='identity_wallet_unique_when_set',
        ),
        migrations.RemoveConstraint(
            model_name='seekerprofile',
            name='identity_bound_requires_wallet_and_user',
        ),
        migrations.RemoveIndex(
            model_name='seekerprofile',
            name='accounts_se_binding_c6adf3_idx',
        ),
        migrations.RemoveIndex(
            model_name='seekerprofile',
            name='accounts_se_primary_6d2218_idx',
        ),
        migrations.RemoveField(
            model_name='seekerprofile',
            name='binding_state',
        ),
        migrations.RemoveField(
            model_name='seekerprofile',
            name='bound_at',
        ),
        migrations.RemoveField(
            model_name='seekerprofile',
            name='bound_via',
        ),
        migrations.RemoveField(
            model_name='seekerprofile',
            name='primary_email',
        ),
        migrations.RemoveField(
            model_name='seekerprofile',
            name='primary_phone',
        ),
        migrations.RemoveField(
            model_name='seekerprofile',
            name='wallet_address',
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='citizenship_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='citizenship_verified_by',
            field=models.ForeignKey(blank=True, help_text='The approved issuer that attested to the citizenship number.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='identity_level',
            field=models.CharField(choices=[('EMAIL_ONLY', 'Email confirmed'), ('CITIZENSHIP', 'Citizenship number verified by an issuer')], default='EMAIL_ONLY', help_text='What a verifier may rely on. Drives the subject-match guarantee.', max_length=20),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Name as it appears on credentials. Set from the first issuance.', max_length=150),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='national_id_hmac',
            field=models.CharField(blank=True, default='', help_text='HMAC-SHA256 of the citizenship number. Blank when not supplied.', max_length=64),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='seekerprofile',
            index=models.Index(fields=['identity_level'], name='accounts_se_identit_12506e_idx'),
        ),
        migrations.AddConstraint(
            model_name='seekerprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('national_id_hmac', ''), _negated=True), fields=('national_id_hmac',), name='identity_national_id_unique_when_set'),
        ),
        migrations.AddConstraint(
            model_name='seekerprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('identity_level', 'CITIZENSHIP'), _negated=True), models.Q(('national_id_hmac', ''), _negated=True), _connector='OR'), name='identity_citizenship_level_requires_number'),
        ),
    ]
