# Generated by Django 5.1.4 on 2026-07-30 13:56

import apps.common.validators
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuanceBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_type', models.CharField(choices=[('ACADEMIC', 'Academic credential'), ('EXPERIENCE', 'Work experience'), ('CERTIFICATION', 'Professional certification')], max_length=20)),
                ('source_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PARSING', 'Parsing'), ('PARTIAL', 'Completed with errors'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PARSING', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('accepted_rows', models.PositiveIntegerField(default=0)),
                ('rejected_rows', models.PositiveIntegerField(default=0)),
                ('anchor_tx_hash', models.CharField(blank=True, max_length=66)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credentials_issuancebatch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CredentialRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_type', models.CharField(choices=[('ACADEMIC', 'Academic credential'), ('EXPERIENCE', 'Work experience'), ('CERTIFICATION', 'Professional certification')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Awaiting issuer endorsement'), ('REJECTED', 'Rejected by issuer'), ('PENDING_ANCHOR', 'Awaiting ledger anchor'), ('ISSUED', 'Issued and anchored'), ('REVOKED', 'Revoked'), ('SUPERSEDED', 'Superseded by a correction')], db_index=True, default='DRAFT', max_length=20)),
                ('issuance_mode', models.CharField(choices=[('AUTHORITY_PUSH', 'Pushed by the issuing authority'), ('SEEKER_CLAIM', 'Claimed by the seeker, endorsed by the issuer')], default='AUTHORITY_PUSH', max_length=20)),
                ('subject_email', models.EmailField(help_text='How a pushed record finds its owner. An institution issues at graduation, before the graduate has an account; the record links itself when they sign up with this address.', max_length=254)),
                ('subject_full_name', models.CharField(help_text='Name as it appears on the credential. Part of the hashed payload.', max_length=150)),
                ('record_hash', models.CharField(blank=True, help_text='keccak256 of the canonical payload, lowercase hex, no 0x prefix.', max_length=64, validators=[apps.common.validators.validate_record_hash])),
                ('canonical_payload', models.JSONField(blank=True, default=dict, help_text='Frozen snapshot of exactly what was hashed at issuance. Kept for audit and for showing verifiers the pre-image — never trusted as the source of truth during verification, which always recomputes from the live detail rows.')),
                ('dedupe_key', models.CharField(blank=True, max_length=64)),
                ('document', models.FileField(blank=True, null=True, upload_to='credentials/%Y/%m/', validators=[apps.common.validators.UploadValidator()])),
                ('document_sha256', models.CharField(blank=True, max_length=64)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_records', to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, help_text='Null until the subject registers an account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='accounts.seekerprofile')),
                ('superseded_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='credentials.credentialrecord')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='credentials.issuancebatch')),
            ],
            options={
                'db_table': 'credentials_credentialrecord',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchRowError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('raw_row', models.JSONField(default=dict)),
                ('error', models.TextField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='credentials.issuancebatch')),
            ],
            options={
                'db_table': 'credentials_batchrowerror',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='AcademicDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(help_text='Roll or registration number issued by the institution.', max_length=64)),
                ('degree_title', models.CharField(max_length=200)),
                ('major', models.CharField(blank=True, max_length=150)),
                ('level', models.CharField(choices=[('SCHOOL', 'School Leaving Certificate'), ('PLUS_TWO', 'Higher Secondary (+2)'), ('DIPLOMA', 'Diploma'), ('BACHELORS', "Bachelor's"), ('MASTERS', "Master's"), ('DOCTORATE', 'Doctorate'), ('CERTIFICATE', 'Certificate course')], max_length=20)),
                ('graduation_date', models.DateField(help_text='Gregorian. This is the canonical date.')),
                ('graduation_date_bs', models.CharField(blank=True, help_text='Bikram Sambat date as printed on the certificate, e.g. 2081-04-15. Display only: the Gregorian date is what gets hashed, because BS conversion tables differ between sources and a hash must not depend on which table the issuer used.', max_length=12)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('4'))])),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('honours', models.CharField(blank=True, max_length=100)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_detail', to='credentials.credentialrecord')),
            ],
            options={
                'db_table': 'credentials_academicdetail',
                'indexes': [models.Index(fields=['registration_number'], name='credentials_registr_a0f905_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cgpa__isnull', True), models.Q(('cgpa__gte', 0), ('cgpa__lte', 4)), _connector='OR'), name='academic_cgpa_range'), models.CheckConstraint(condition=models.Q(('percentage__isnull', True), models.Q(('percentage__gte', 0), ('percentage__lte', 100)), _connector='OR'), name='academic_percentage_range')],
            },
        ),
        migrations.CreateModel(
            name='ExperienceDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('CONSULTANT', 'Consultant')], default='FULL_TIME', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Null while the employee is still with the company.', null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('departure_status', models.CharField(choices=[('CURRENT', 'Currently employed'), ('RESIGNED', 'Resigned'), ('CONTRACT_ENDED', 'Contract ended'), ('RETIRED', 'Retired'), ('TERMINATED', 'Terminated')], max_length=20)),
                ('responsibilities', models.TextField(blank=True, help_text='Ordered list is preserved in the hash; wording matters.')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experience_detail', to='credentials.credentialrecord')),
            ],
            options={
                'db_table': 'credentials_experiencedetail',
                'indexes': [models.Index(fields=['job_title'], name='credentials_job_tit_b07d2b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('end_date__isnull', True), ('is_current', True)), models.Q(('end_date__isnull', False), ('is_current', False)), _connector='OR'), name='experience_current_xor_end_date'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='experience_end_after_start')],
            },
        ),
        migrations.AddIndex(
            model_name='issuancebatch',
            index=models.Index(fields=['organization', '-created_at'], name='credentials_organiz_04fac2_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialrecord',
            index=models.Index(fields=['issuer', 'status'], name='credentials_issuer__074c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialrecord',
            index=models.Index(fields=['subject', 'record_type'], name='credentials_subject_6f46c3_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialrecord',
            index=models.Index(fields=['subject_email'], name='credentials_subject_153148_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialrecord',
            index=models.Index(fields=['status', '-created_at'], name='credentials_status_b63942_idx'),
        ),
        migrations.AddConstraint(
            model_name='credentialrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('record_hash', ''), _negated=True), fields=('record_hash',), name='record_hash_unique_when_set'),
        ),
        migrations.AddConstraint(
            model_name='credentialrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING_ANCHOR', 'ISSUED', 'REVOKED', 'SUPERSEDED']), models.Q(('dedupe_key', ''), _negated=True)), fields=('dedupe_key',), name='record_dedupe_unique_while_live'),
        ),
        migrations.AddConstraint(
            model_name='credentialrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ISSUED'), _negated=True), ('issued_at__isnull', False), _connector='OR'), name='record_issued_requires_issued_at'),
        ),
        migrations.AddConstraint(
            model_name='credentialrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['PENDING_ANCHOR', 'ISSUED', 'REVOKED', 'SUPERSEDED']), _negated=True), models.Q(('record_hash', ''), _negated=True), _connector='OR'), name='record_live_requires_hash'),
        ),
    ]
