# Generated by Django 5.1.4 on 2026-08-01 06:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_email_primary_identity'),
        ('credentials', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('sent_to', models.EmailField(help_text='The address the issuer supplied. Recorded for dispute resolution.', max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Failed redemption attempts. Bounded to stop token guessing.')),
                ('send_count', models.PositiveSmallIntegerField(default=1)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'credentials_confirmation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='credentialrecord',
            name='record_dedupe_unique_while_live',
        ),
        migrations.RemoveConstraint(
            model_name='credentialrecord',
            name='record_live_requires_hash',
        ),
        migrations.AddField(
            model_name='credentialrecord',
            name='decline_reason',
            field=models.TextField(blank=True, help_text="Optional note from the holder. Feeds the issuer's correction flow."),
        ),
        migrations.AddField(
            model_name='credentialrecord',
            name='offer_expires_at',
            field=models.DateTimeField(blank=True, help_text='After this the confirmation link stops working and the offer lapses.', null=True),
        ),
        migrations.AddField(
            model_name='credentialrecord',
            name='offered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credentialrecord',
            name='subject_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credentialrecord',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OFFERED', "Awaiting the holder's confirmation"), ('DECLINED', 'Declined by the holder'), ('EXPIRED', 'Confirmation link expired'), ('PENDING_REVIEW', 'Awaiting issuer endorsement'), ('REJECTED', 'Rejected by issuer'), ('PENDING_ANCHOR', 'Awaiting ledger anchor'), ('ISSUED', 'Issued and anchored'), ('REVOKED', 'Revoked'), ('SUPERSEDED', 'Superseded by a correction')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='credentialrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OFFERED', 'PENDING_ANCHOR', 'ISSUED', 'REVOKED', 'SUPERSEDED']), models.Q(('dedupe_key', ''), _negated=True)), fields=('dedupe_key',), name='record_dedupe_unique_while_live'),
        ),
        migrations.AddConstraint(
            model_name='credentialrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['OFFERED', 'PENDING_ANCHOR', 'ISSUED', 'REVOKED', 'SUPERSEDED']), _negated=True), models.Q(('record_hash', ''), _negated=True), _connector='OR'), name='record_live_requires_hash'),
        ),
        migrations.AddField(
            model_name='credentialconfirmation',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='credentials.credentialrecord'),
        ),
        migrations.AddIndex(
            model_name='credentialconfirmation',
            index=models.Index(fields=['expires_at'], name='credentials_expires_7c1dd5_idx'),
        ),
    ]
