# Generated by Django 5.1.4 on 2026-08-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_consent_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialrecord',
            name='binding_salt',
            field=models.CharField(blank=True, help_text='Per-record salt. Off-chain only — this is what stops cross-record correlation.', max_length=32),
        ),
        migrations.AddField(
            model_name='credentialrecord',
            name='subject_binding',
            field=models.CharField(blank=True, help_text="Salted HMAC of the holder's citizenship number. Blank when they have none.", max_length=64),
        ),
    ]
