# Generated by Django 5.1.4 on 2026-07-30 13:56

import apps.common.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('INSTITUTION', 'Educational institution'), ('EMPLOYER', 'Employer')], max_length=20)),
                ('legal_name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('registration_number', models.CharField(help_text='PAN/VAT number for employers, UGC accreditation number for institutions.', max_length=64)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('status_reason', models.TextField(blank=True, help_text='Why the organisation was rejected or suspended.')),
                ('chain_address', models.CharField(blank=True, help_text='Custodial signing address. Generated by the platform on approval.', max_length=42, validators=[apps.common.validators.validate_eth_address])),
                ('approval_tx_hash', models.CharField(blank=True, max_length=66)),
                ('approved_on_chain_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations_organization',
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='IssuerKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=42, validators=[apps.common.validators.validate_eth_address])),
                ('encrypted_private_key', models.BinaryField(help_text='Fernet ciphertext. The key never exists in plaintext at rest.')),
                ('key_version', models.PositiveSmallIntegerField(default=1)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issuer_key', to='organizations.organization')),
            ],
            options={
                'db_table': 'organizations_issuerkey',
            },
        ),
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('ACCREDITATION', 'Accreditation certificate'), ('REGISTRATION', 'Company/PAN registration'), ('AUTHORISATION', 'Letter of authorisation'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='org-documents/%Y/%m/', validators=[apps.common.validators.UploadValidator()])),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ISSUER', 'Issuer'), ('VIEWER', 'Viewer')], default='ISSUER', max_length=20)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations_membership',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro')], default='FREE', max_length=10)),
                ('monthly_lookup_limit', models.PositiveIntegerField(default=50, help_text='0 means unlimited (PRO).')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization')),
            ],
            options={
                'db_table': 'organizations_subscription',
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status', 'kind'], name='organizatio_status_4895c4_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['kind'], name='organizatio_kind_77e301_idx'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('kind', 'registration_number'), name='org_unique_registration_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('chain_address', ''), _negated=True), fields=('chain_address',), name='org_unique_chain_address_when_set'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), models.Q(('chain_address', ''), _negated=True), _connector='OR'), name='org_approved_requires_chain_address'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'role'], name='organizatio_organiz_e82976_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='membership_unique_user_org'),
        ),
    ]
